site_name: Site pro de <Ton Nom>
theme:
  name: material
  language: fr
nav:
  - Accueil: index.md
  - Plan du cours: cours.md
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true
